//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputS/NewCharControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewCharControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewCharControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewCharControls"",
    ""maps"": [
        {
            ""name"": ""Sheep"",
            ""id"": ""70663342-0e03-44c0-a805-ba647926eb5e"",
            ""actions"": [
                {
                    ""name"": ""Sheep_Movement"",
                    ""type"": ""Value"",
                    ""id"": ""f223588a-5bea-4230-9396-59ee481eaf58"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Exit_btn"",
                    ""type"": ""Button"",
                    ""id"": ""7cd849f6-40aa-4b07-a367-ec87f42814fe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""9b3ad4d7-b237-419d-bc70-73b4275eddcc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheep_Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""859ab501-239e-487b-b1d7-7c29200ed404"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheep_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8845c810-e23c-4a9a-b6a3-8cdc23323de5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheep_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""928a52c0-28c6-4ebd-a85f-f05a8639252b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheep_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2a8de7de-2cd2-43b8-93e8-5dc69e8c27ec"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sheep_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9ef205df-278d-4c97-9d88-7bed7c785b77"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit_btn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Sheep
        m_Sheep = asset.FindActionMap("Sheep", throwIfNotFound: true);
        m_Sheep_Sheep_Movement = m_Sheep.FindAction("Sheep_Movement", throwIfNotFound: true);
        m_Sheep_Exit_btn = m_Sheep.FindAction("Exit_btn", throwIfNotFound: true);
    }

    ~@NewCharControls()
    {
        UnityEngine.Debug.Assert(!m_Sheep.enabled, "This will cause a leak and performance issues, NewCharControls.Sheep.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Sheep
    private readonly InputActionMap m_Sheep;
    private List<ISheepActions> m_SheepActionsCallbackInterfaces = new List<ISheepActions>();
    private readonly InputAction m_Sheep_Sheep_Movement;
    private readonly InputAction m_Sheep_Exit_btn;
    public struct SheepActions
    {
        private @NewCharControls m_Wrapper;
        public SheepActions(@NewCharControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Sheep_Movement => m_Wrapper.m_Sheep_Sheep_Movement;
        public InputAction @Exit_btn => m_Wrapper.m_Sheep_Exit_btn;
        public InputActionMap Get() { return m_Wrapper.m_Sheep; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SheepActions set) { return set.Get(); }
        public void AddCallbacks(ISheepActions instance)
        {
            if (instance == null || m_Wrapper.m_SheepActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SheepActionsCallbackInterfaces.Add(instance);
            @Sheep_Movement.started += instance.OnSheep_Movement;
            @Sheep_Movement.performed += instance.OnSheep_Movement;
            @Sheep_Movement.canceled += instance.OnSheep_Movement;
            @Exit_btn.started += instance.OnExit_btn;
            @Exit_btn.performed += instance.OnExit_btn;
            @Exit_btn.canceled += instance.OnExit_btn;
        }

        private void UnregisterCallbacks(ISheepActions instance)
        {
            @Sheep_Movement.started -= instance.OnSheep_Movement;
            @Sheep_Movement.performed -= instance.OnSheep_Movement;
            @Sheep_Movement.canceled -= instance.OnSheep_Movement;
            @Exit_btn.started -= instance.OnExit_btn;
            @Exit_btn.performed -= instance.OnExit_btn;
            @Exit_btn.canceled -= instance.OnExit_btn;
        }

        public void RemoveCallbacks(ISheepActions instance)
        {
            if (m_Wrapper.m_SheepActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISheepActions instance)
        {
            foreach (var item in m_Wrapper.m_SheepActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SheepActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SheepActions @Sheep => new SheepActions(this);
    public interface ISheepActions
    {
        void OnSheep_Movement(InputAction.CallbackContext context);
        void OnExit_btn(InputAction.CallbackContext context);
    }
}
